lib/shared.js
I was checking out @typescript-eslint and was looking for a TypeScript port of the Airbnb configuration, and discovered this repository, many thanks! 👏🏻
I discovered that when importing an interface from a module, `eslint` would complain it is an unused var. So I checked out what the recommended config for @typescript-eslint's `eslint-plugin` did (https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/src/configs/recommended.json#L32-L33).
I feel it would make a good addition to this plugin as the normal JavaScript rule is enabled in `eslint-config-airbnb-base` (https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb-base/rules/variables.js#L39) so enabling the TypeScript "equivalent" makes sense.
=> feat: add @typescript-eslint/no-unused-vars rule

index.js, lib/shared.js
These rules are now replaced with equivalent 'typescript-eslint' rules.
BREAKING CHANGE: Config may find additional linting errors for: `camelcase`, `indent`, `no-array-constructor`, and `no-unused-vars`.
Thanks to @tombell for raising this original issue in #3  👏
=> Disable eslint rules that are incompatible with typescript

README.md, index.js, lib/shared.js
We are currently applying the linting settings and rules to TS files only. However, this is *not* necessary, as the same config works on both JS and TS files.
The current config also makes overriding rules more difficult, as reported by @dawidk92 in #4.
This PR makes the linting rules and settings more generic, and will lint all files passed into ESLint (JS and/or TS files).
=> Lint both JS and TS files

README.md, lib/shared.js, lint-staged.config.js, package-lock.json, package.json
BREAKING CHANGE:
New and updated linting rules bubbled up from latest Airbnb version.
New dependencies and dependency versions required within your app.
Using `airbnb-typescript`?
```
npm install eslint-config-airbnb-typescript@latest \
eslint-plugin-import@^2.18.2 \
eslint-plugin-jsx-a11y@^6.2.3 \
eslint-plugin-react@^7.14.3 \
eslint-plugin-react-hooks@^1.7.0 \
@typescript-eslint/eslint-plugin@^2.3.0 \
--save-dev
```
Using `airbnb-typescript/base` (no React support)?
```
npm install eslint-config-airbnb-typescript@latest \
eslint-plugin-import@^2.18.2 \
@typescript-eslint/eslint-plugin@^2.3.0 \
--save-dev
```
=> Update dependencies, support ESLint v6

lib/shared.js
Fixes https://github.com/iamturns/eslint-config-airbnb-typescript/issues/19
=> Remove arrow-parens rule override

lib/shared.js, package.json
In order to improve the maintainability of the package, direct imports should be applied instead of copying rules.
=> Extend base config rules directly

lib/shared.js
By replacing 'no-unused-expressions' with its '@typescript-eslint' equivalent.
=> Add support for optional chaining

lib/shared.js
=> Fix incorrect `no-undef` errors when exporting default interfaces

lib/shared.js
=> Fix `no-dupe-class-members` error when overloading methods

.eslintrc.js, README.md, lib/shared.js, package-lock.json, package.json, tsconfig.json
Includes support for latest TypeScript version.
Fixes #53.
**BREAKING CHANGE 1**
New rules require type information from your `tsconfig.json` file.
You must set [parserOptions.project](https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/parser#parseroptionsproject) within your ESLint config file.
Example ESLint config:
```
module.exports = {
extends: ['airbnb-typescript'],
parserOptions: {
project: './tsconfig.json'
}
}
```
**BREAKING CHANGE 2**
You must upgrade your local dependency of `@typescript-eslint/eslint-plugin` to `2.19.0`.
Example command: `npm install @typescript-eslint/eslint-plugin@^2.19.0 --save-dev`.
=> fix: Update to latest `@typescript-eslint`

lib/shared.js
As TypeScript already checks for the existence of modules, the [`import/no-unresolved`](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-unresolved.md) rule is redundant.
=> fix: module resolution checks in monorepos

README.md, lib/shared.js, package-lock.json, package.json
BREAKING CHANGE: Dropped support for Node 8
BREAKING CHANGE: Dropped support for TypeScript 3.2
=> feat: Update to @typescript-eslint v3.1.0

lib/shared.js
=> fix: Allow PascalCase variables for React components

README.md, lib/shared.js, package-lock.json, package.json
I followed the steps inside the [changelog of typescript-eslint](https://github.com/typescript-eslint/typescript-eslint/releases/tag/v4.0.0). Additionally, I've re-enabled a rule which used to report false positives, but should be fixed by now (see [here](https://github.com/iamturns/eslint-config-airbnb-typescript/issues/50)).
=> chore(deps)!: upgrade to typescript-eslint v4

lib/shared.js
[typescript-eslint's no implied eval](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-implied-eval.md) merges two ESLint rules: [no-implied-eval](https://eslint.org/docs/rules/no-implied-eval) and [no-new-func](https://eslint.org/docs/rules/no-new-func) (and also blocks setImmediate, which i couldn't find a vanilla ESLint equivalent). Currently, using the following code outputs redundant errors:
```ts
/*
Implied eval. Do not use the Function constructor to create functions. eslint(@typescript-eslint/no-implied-eval)
The Function constructor is eval. eslint(no-new-func)
*/
const x = new Function('a', 'b', 'return a + b');
```
=> Disable no new func

lib/shared.js
Sync up with airbnb [`no-loop-func`](https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb-base/rules/best-practices.js#L157) rule
=> Added `no-loop-func` rule

index.js, lib/shared.js
This PR makes configs consistent with eslint-plugin-import's [`plugin:import/typescript` rules](https://github.com/benmosher/eslint-plugin-import/blob/master/config/typescript.js).
Resolves #125.
=> feat: implement 'plugin:import/typescript' rules

.eslintrc.js, README.md, base.js, index.js, lib/shared.js, package.json, renovate.json
Fixes #6, #207 
BREAKING CHANGE: Install `eslint-config-airbnb` (or `eslint-config-airbnb-base`) and `@typescript-eslint/parser` as dependencies. Follow the updated README.md file.
=> fix: Remove warnings on installation

package.json
BREAKING CHANGE: Peer dependency update. Update @typescript-eslint/eslint-plugin and @typescript-eslint/parser to ^5.0.0.
=> chore(deps): Peer dependencies to latest major version

lib/shared.js
Replace rules with '@typescript-eslint' version (default-param-last, no-loss-of-precision) and disable React prop types rules (react/prop-types, react/default-props-match-prop-types)
=> Replace rules with '@typescript-eslint' version and disable React prop types rules

lib/shared.js
The value for no-return-await from airbnb was being incorrectly mapped to return-await (https://typescript-eslint.io/rules/return-await/)
This was effectively linting the opposite of what it should and forcing the code to always add await to the return instead of disallowing it.
=> fix: Enforce airbnb-base no-return-await intention

package.json
I believe this is ok as a non-breaking change as this package pretty much implicitly requires **eslint** and **eslint-plugin-import**, right?
Fixes #274
See also: https://github.com/iamturns/eslint-config-airbnb-typescript/issues/207#issuecomment-1030420694
=> Surface peer dependencies of eslint-config-airbnb-base dependency

lib/shared.js
It's currently unclear why some rules have been disabled.
=> Add documentation to disabled rules

README.md
Instead of suggesting softly that users 'see' one or the other base configs, I figured I could make this change to help those just getting started realize that they will need to pick the right base. 
Hopefully this might reduce the time spent researching the differences.
=> docs(README.md): edit step 1 of Setup to provide a stronger, easier to read sentence for those getting started

lib/shared.js
Replace airbnb [`space-before-blocks`](https://github.com/airbnb/javascript/blob/eslint-config-airbnb-v19.0.4/packages/eslint-config-airbnb-base/rules/style.js#L472) with [`@typescript-eslint/space-before-blocks`](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/space-before-blocks.md) version
=> Replace 'space-before-blocks' with '@typescript-eslint' version

README.md, package.json
`space-before-blocks` is only added in [@typescript-eslint/eslint-plugin@5.13.0](https://github.com/typescript-eslint/typescript-eslint/blob/main/CHANGELOG.md#5130-2022-02-28) peerDependencies & README should be updated to reflect that.
=> chore: bumped peerDependencies to reflect the use of space-before-blocks

DEVELOPING.md, README.md, package-lock.json, package.json
@iamturns hey!
Sorry for the notice. `typescript-eslint` recently released version 6 with a large set of changes: https://typescript-eslint.io/blog/announcing-typescript-eslint-v6/ . Unfortunately, without changing the peer-deps of your package, we cannot upgrade.
~Also i removed those dependencies from dev-deps. It looks like they are not involved in any way during the development of the package. If i am wrong please tell me and i will get back and update them.~ It was reverted.
I tested the package locally in my codebase and didn't find any problems.
I will be grateful for the review and release of the new version. I don't see any visible changes to how this package works, so this shouldn't be a breaking change for users.
Closed …
=> Update @typescript-eslint to v6
